import type { Plugin } from "vite";
import { getListOpensyaConfig } from "../../../config/load.js";
import fs from "node:fs";
import { getChildren } from "../../../utils/get-children.js";
import path from "node:path";
import _ from "lodash";
import { getDirs } from "@/utils/dirs.js";
import { random } from "@/utils/random.js";
import { loadJs } from "@/utils/load-js.js";
import { atomicWriteFile } from "@/utils/atomic-write-file.js";
import { normalizeDir } from "@/utils/normalize-dir.js";

const VIRTUAL_ID = "virtual:composables";
const RESOLVED_VIRTUAL_ID = "\0virtual:composables";

const template = `
import { unset } from "{{import_unset}}";

{{imports}}

{{assigns}}
`;

const dtsTemplate = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-opensya-composables

declare global {
{{dtsEntries}}
}

export {}
`;

export function viteComposablesPlugin(): Plugin {
  let composablesEntries: Array<{ file: string; name: string }> = [];

  async function getComposables(parentDir: string) {
    if (!fs.existsSync(parentDir)) return;

    const files = getChildren(parentDir, {
      recursive: true,
      onlyFile: true,
      endWith: /\.(js|ts)$/,
    });

    for (const file of files) {
      const name = _.camelCase(file.name.replace(/\.(js|ts)$/, ""));
      let slug = "";

      while (
        composablesEntries.filter((ce) => ce.name === `${name}${slug}`).length
      ) {
        slug = `_${random({ length: 8, digits: false, specialChars: false })}`;
      }

      composablesEntries.push({ file: file.path, name: `${name}${slug}` });
    }
  }

  // Génère le fichier d'autocomplétion TypeScript (composables.d.ts)
  async function generateDtsFile(): Promise<void> {
    const { OUTPUT_DIR_CLIENT } = getDirs();
    const dtsPath = path.resolve(OUTPUT_DIR_CLIENT, "composables.d.ts");
    const dtsEntries = [];

    for (const entry of composablesEntries) {
      const content = await loadJs<Record<string, unknown>>(entry.file);

      dtsEntries.push(
        ...Object.keys(content)
          .filter((composableName) => composableName !== "default")
          .map((composableName) => {
            const rPath = normalizeDir(
              path.relative(OUTPUT_DIR_CLIENT, entry.file),
            );

            return `  const ${composableName}: (typeof import('${rPath}'))['${composableName}']`;
          }),
      );
    }

    atomicWriteFile(
      dtsPath,
      dtsTemplate.replace("{{dtsEntries}}", dtsEntries.join("\n")),
    );
  }

  async function generateCode() {
    composablesEntries = [];

    const configs = _.reverse(getListOpensyaConfig());

    for (const { _srcDir } of configs) {
      const parentDir = path.resolve(_srcDir, "app/composables");
      if (!fs.existsSync(parentDir)) continue;

      await getComposables(parentDir);
    }

    // On lance la génération du fichier de types parallèlement
    await generateDtsFile();

    const imports = composablesEntries
      .map(({ file, name }) => {
        const rPath = normalizeDir(path.relative(process.cwd(), file));
        return `import * as ${name} from "${rPath}";`;
      })
      .join("\n");

    const assigns = composablesEntries
      .map(({ name }) =>
        [
          `unset(${name}, 'default');`,
          `Object.assign(globalThis, ${name});`,
        ].join("\n"),
      )
      .join("\n");

    return template
      .replace(
        "{{import_unset}}",
        normalizeDir(
          path.relative(
            process.cwd(),
            path.resolve(import.meta.dirname, "../../../utils/unset.js"),
          ),
        ),
      )
      .replace("{{imports}}", imports)
      .replace("{{assigns}}", assigns);
  }

  return {
    name: "vite-opensya-composables",
    enforce: "pre",

    resolveId(id) {
      if (id === VIRTUAL_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;

      return generateCode();
    },
  };
}
