/* eslint-disable @typescript-eslint/no-explicit-any */

import { createUnplugin } from "unplugin";
import { parse } from "acorn";
import { walk as simpleWalk } from "estree-walker";
import MagicString from "magic-string";
import { findStaticImports, parseStaticImport } from "mlly";
import type { Node, Program } from "estree";
import { getDirs } from "@/utils/dirs.js";
import { normalizeDir } from "@/utils/normalize-dir.js";
import path from "node:path";
import { atomicWriteFile } from "@/utils/atomic-write-file.js";

const HAS_MACRO_RE = /\bdefinePageMeta\s*\(\s*/;

export interface AppMetaPluginOptions {
  dev?: boolean;
}

const dtsTemplate = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-opensya-plugins

declare global {
  const definePageMeta: (typeof import("{{helper_page_meta}}"))['definePageMeta'];
}

export {};
`;

export const vitePageMetaPlugin = (options: AppMetaPluginOptions = {}) =>
  createUnplugin(() => {
    async function generateDtsFile(): Promise<void> {
      const { OUTPUT_DIR_CLIENT } = getDirs();
      const dtsPath = path.resolve(OUTPUT_DIR_CLIENT, "page-meta.d.ts");

      const helperRouterMiddle = normalizeDir(
        path.relative(
          OUTPUT_DIR_CLIENT,
          path.resolve(import.meta.dirname, "../app/helpers/page-meta.js"),
        ),
      );

      try {
        atomicWriteFile(
          dtsPath,
          dtsTemplate.replace("{{helper_page_meta}}", helperRouterMiddle),
        );
      } catch (error) {
        console.error("[Vite Plugin] Failed to write page-meta.d.ts:", error);
      }
    }

    return {
      name: "opensya-page-meta-plugin",
      enforce: "post",
      transform: {
        // On ne s'active que si le fichier contient la macro
        code: { include: HAS_MACRO_RE },
        async handler(code, id) {
          await generateDtsFile();

          // 1. Si on n'est pas en mode macro, on ne fait rien
          if (!id.includes("macro=true")) {
            return null;
          }

          const s = new MagicString(code);
          const imports = findStaticImports(code);

          // 2. Construire la carte des imports
          const importMap = new Map<string, string>();
          for (const i of imports) {
            const parsed = parseStaticImport(i);
            const names = [
              parsed.defaultImport,
              ...Object.values(parsed.namedImports || {}),
              parsed.namespacedImport,
            ].filter(Boolean) as string[];

            for (const name of names) {
              importMap.set(name, i.code.trim());
            }
          }

          // 3. Parser le code en AST avec tolérance pour le JS moderne
          const ast = parse(code, {
            ecmaVersion: "latest",
            sourceType: "module",
            allowImportExportEverywhere: true,
            allowHashBang: true,
          }) as unknown as Program;

          // 4. Trouver les déclarations de variables top-level (pour le hoisting)
          const topLevelDeclarations = new Map<string, Node>();
          for (const node of ast.body) {
            if (node.type === "VariableDeclaration") {
              for (const decl of node.declarations) {
                if (decl.id.type === "Identifier") {
                  topLevelDeclarations.set(decl.id.name, node);
                }
              }
            } else if (node.type === "FunctionDeclaration" && node.id) {
              topLevelDeclarations.set(node.id.name, node);
            }
          }

          // 5. Préparer les conteneurs pour les dépendances extraites
          const addedImports = new Set<string>();
          const addedDeclarations = new Set<string>();

          function addImport(name: string) {
            const importCode = importMap.get(name);
            if (importCode && !addedImports.has(importCode)) {
              addedImports.add(importCode);
            }
          }

          function processDeclaration(node: Node) {
            // Utilisation d'un cast temporaire car acorn n'expose pas toujours .start/.end directement sur Node
            const start = (node as any).start;
            const end = (node as any).end;
            const codeSectionKey = `${start}-${end}`;
            if (addedDeclarations.has(codeSectionKey)) return;

            addedDeclarations.add(codeSectionKey);

            // On cherche les dépendances de cette déclaration
            simpleWalk(node, {
              enter(innerNode: any, parent: any) {
                if (innerNode.type !== "Identifier") return;
                // Ignorer les clés d'objet ou les déclarations de variables locales
                if (
                  parent?.type === "Property" &&
                  parent.key === innerNode &&
                  !parent.computed
                )
                  return;
                if (
                  parent?.type === "VariableDeclarator" &&
                  parent.id === innerNode
                )
                  return;

                const name = innerNode.name;
                if (importMap.has(name)) {
                  addImport(name);
                } else if (topLevelDeclarations.has(name)) {
                  // Récursion : on extrait aussi la déclaration de cette dépendance
                  processDeclaration(topLevelDeclarations.get(name)!);
                }
              },
            });
          }

          // 6. Trouver et traiter l'appel à definePageMeta()
          let metaNode: any = null;

          simpleWalk(ast, {
            enter(node: any) {
              if (
                node.type === "CallExpression" &&
                node.callee.type === "Identifier" &&
                node.callee.name === "definePageMeta"
              ) {
                if (node.arguments[0]) {
                  metaNode = node.arguments[0];
                }
              }
            },
          });

          if (metaNode === null) return null;

          // 7. Extraire les identifiants utilisés DANS la macro
          simpleWalk(metaNode, {
            enter(node: any, parent: any) {
              if (node.type !== "Identifier") return;
              // Ignorer les clés d'objets (ex: { layout: "foo" } -> "layout" n'est pas une variable)
              if (
                parent?.type === "Property" &&
                parent.key === node &&
                !parent.computed
              )
                return;

              const name = node.name;
              if (importMap.has(name)) {
                addImport(name);
              } else if (topLevelDeclarations.has(name)) {
                // Hoisting : on extrait la déclaration externe et ses dépendances
                processDeclaration(topLevelDeclarations.get(name)!);
              }
            },
          });

          // 8. Assembler le code final
          const metaCode = code.slice(metaNode.start, metaNode.end);

          const declarationsCode = Array.from(addedDeclarations)
            // Trier par position dans le fichier source pour préserver l'ordre de déclaration
            .map((key) => {
              const [start, end] = key.split("-").map(Number);
              return code.slice(start, end);
            })
            .join("\n");

          const importsCode = Array.from(addedImports).join("\n");

          const hmrCode = options.dev
            ? `
if (import.meta.hot) {
  import.meta.hot.accept(mod => {
    Object.assign(__page_meta, mod)
  })
}`
            : "";

          const extractedCode = [
            importsCode,
            declarationsCode,
            `const __page_meta = ${metaCode}\nexport default __page_meta`,
            hmrCode,
          ]
            .filter(Boolean)
            .join("\n");

          s.overwrite(0, code.length, extractedCode.trim());

          return {
            code: s.toString(),
            map: s.generateMap({ source: id, hires: true }),
          };
        },
      },
      // 9. HMR pour Vite
      vite: {
        handleHotUpdate: {
          order: "post",
          handler({ file, server }) {
            // Invalider le module miroir quand le fichier d'origine change
            const macroModule = server.moduleGraph.getModuleById(
              file + "?macro=true",
            );
            if (macroModule) {
              return [macroModule];
            }
          },
        },
      },
    };
  });
