import { getListOpensyaConfig } from "@/config/load.js";
import { atomicWriteFile } from "@/utils/atomic-write-file.js";
import { getDirs } from "@/utils/dirs.js";
import { getChildren } from "@/utils/get-children.js";
import { normalizeDir } from "@/utils/normalize-dir.js";
import _ from "lodash";
import fs from "node:fs";
import path from "node:path";
import type { Plugin, ViteDevServer } from "vite";

// Alignement sur l'import de ton routeur
const VIRTUAL_ID = "virtual:router-middlewares";
const RESOLVED_VIRTUAL_ID = "\0virtual:router-middlewares";

const dtsTemplate = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-opensya-plugins

declare global {
  const defineRouteMiddleware: (typeof import("{{helper_router_middleware}}"))['defineRouteMiddleware'];
}

export {};
`;

async function generateDtsFile(): Promise<void> {
  const { OUTPUT_DIR_CLIENT } = getDirs();
  const dtsPath = path.resolve(OUTPUT_DIR_CLIENT, "router.d.ts");

  const helperRouterMiddle = normalizeDir(
    path.relative(
      OUTPUT_DIR_CLIENT,
      path.resolve(import.meta.dirname, "../app/helpers/router-middleware.js"),
    ),
  );

  try {
    atomicWriteFile(
      dtsPath,
      dtsTemplate.replace("{{helper_router_middleware}}", helperRouterMiddle),
    );
  } catch (error) {
    console.error("[Vite Plugin] Failed to write plugins.d.ts:", error);
  }
}

async function generateCode() {
  const middlewareEntries: Record<string, { file: string }> = {};

  async function getMiddlewares(parentDir: string) {
    if (!fs.existsSync(parentDir)) return;

    const files = getChildren(parentDir, {
      onlyFile: true,
      endWith: /\.(js|ts)$/,
    });

    for (const file of files) {
      const name = _.camelCase(
        file.name.replace(/\.global\.(js|ts)$/, "").replace(/\.(js|ts)$/, ""),
      );

      middlewareEntries[name] = { file: file.path };
    }
  }

  // On récupère les configurations Opensya dans l'ordre inverse (priorité aux couches supérieures)
  const configs = _.reverse(getListOpensyaConfig());

  for (const { _srcDir } of configs) {
    const parentDir = path.resolve(_srcDir, "app/middlewares");
    await getMiddlewares(parentDir);
  }

  const imports: string[] = [];
  const globals: string[] = [];
  const named: { [key: string]: string } = {};

  generateDtsFile();

  Object.entries(middlewareEntries).forEach(([middlewareName, meta], index) => {
    const filename = path.basename(meta.file);
    const isGlobal = /\.global\.(ts|js)$/.test(filename);

    const importName = `middleware_${index}`;

    // RÈGLE D'OR : On utilise le chemin absolu normalisé.
    // Vite résout parfaitement les imports absolus système, éliminant tout bug de chemin relatif virtuel.
    const absolutePath = normalizeDir(meta.file);

    imports.push(`import ${importName} from "${absolutePath}";`);

    if (isGlobal) {
      globals.push(importName);
    } else {
      named[middlewareName] = importName;
    }
  });

  const code = `
${imports.join("\n")}

export const globalMiddlewares = [
  ${globals.join(",\n  ")}
];

export const namedMiddlewares = {
  ${Object.entries(named)
    .map(([name, imp]) => `"${name}": ${imp}`)
    .join(",\n  ")}
};
  `.trim();

  return code;
}

export function viteRouterMiddlewaresPlugin(): Plugin {
  let server: ViteDevServer;

  return {
    name: "vite-opensya-router-middlewares",
    enforce: "pre",

    configureServer(_server) {
      server = _server;

      // Détection HMR : Si un fichier est ajouté ou supprimé dans un dossier middlewares,
      // on invalide le module virtuel pour forcer sa reconstruction immédiate.
      const handleFileChange = (file: string) => {
        if (file.includes("app/middlewares")) {
          const module = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID);
          if (module) {
            server.moduleGraph.invalidateModule(module);
            server.ws.send({
              type: "full-reload",
              path: "*",
            });
          }
        }
      };

      server.watcher.on("add", handleFileChange);
      server.watcher.on("unlink", handleFileChange);
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;

      return generateCode();
    },
  };
}
