import type { Plugin } from "vite";
import { getListOpensyaConfig } from "../../../config/load.js";
import fs from "node:fs";
import { getChildren } from "../../../utils/get-children.js";
import path from "node:path";
import _ from "lodash";
import { getDirs } from "#core/utils/dirs.js";

const VIRTUAL_ID = "virtual:components";
const RESOLVED_VIRTUAL_ID = "\0virtual:components";

const template = `
import { defineAsyncComponent } from 'vue';

export const components = {
{{imports}}
};

export const componentsPlugin = {
  install(app) {
    for (const [name, loader] of Object.entries(components)) {
      app.component(name, defineAsyncComponent(loader));
    }
    console.log('[Opensya] Registered global components:', Object.keys(components));
  }
};
`;

const dtsTemplate = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-opensya-components
// Read more: https://github.com/vuejs/core/pull/3399
import 'vue'

declare module 'vue' {
  export interface GlobalComponents {
{{dtsEntries}}
  }
}
`;

export function viteComponentsPlugin(): Plugin {
  let componentsEntries: Record<string, { parent: string; file: string }> = {};

  function getComponentName(parentDir: string, filePath: string): string {
    // Remove the ".global.vue" extension
    const baseName = path
      .relative(parentDir, filePath)
      .replace(/\.global\.vue$/, "");

    // Convert to PascalCase (handles kebab-case, snake_case, and camelCase)
    return baseName
      .replace(/[-_\/]+(.)?/g, (_, char) => (char ? char.toUpperCase() : "")) // kebab/snake -> camelCase
      .replace(/^(.)/, (char) => char.toUpperCase()); // camelCase -> PascalCase
  }

  async function getPages(parentDir: string) {
    if (!fs.existsSync(parentDir)) return;

    const files = getChildren(parentDir, {
      recursive: true,
      onlyFile: true,
      endWith: /\.global.(vue)$/,
    });

    for (const file of files) {
      const name = getComponentName(parentDir, file.path);
      componentsEntries[name] = { parent: parentDir, file: file.path };
    }
  }

  // Generates the TypeScript declaration file (components.d.ts)
  async function generateDtsFile(): Promise<void> {
    const { OUTPUT_DIR_CLIENT } = getDirs();

    const dtsPath = path.resolve(OUTPUT_DIR_CLIENT, "components.d.ts");

    // Build the type definitions for each component
    const dtsEntries = Object.entries(componentsEntries)
      .map(([name, { file }]) => {
        // Calculate the relative path from the dts file to the component
        let relativePath = path
          .relative(path.dirname(dtsPath), file)
          .replace(/\\/g, "/");
        if (!relativePath.startsWith(".")) {
          relativePath = `./${relativePath}`;
        }
        return `  ${name}: typeof import('${relativePath}')['default']`;
      })
      .join("\n");

    const dtsContent = dtsTemplate.replaceAll("{{dtsEntries}}", dtsEntries);

    try {
      fs.writeFileSync(dtsPath, dtsContent, "utf-8");
    } catch (error) {
      console.error("[Vite Plugin] Failed to write components.d.ts:", error);
    }
  }

  // Modified to return the generated JS code as a string
  async function generateCode(): Promise<string> {
    componentsEntries = {};

    const configs = _.reverse(getListOpensyaConfig());

    for (const { _srcDir } of configs) {
      const pageDir = path.resolve(_srcDir, "app/components");
      if (!fs.existsSync(pageDir)) continue;

      await getPages(pageDir);
    }

    // Trigger the dts generation asynchronously
    await generateDtsFile();

    // Generate lazy-loaded imports for Vue
    const imports = Object.entries(componentsEntries)
      .map(([name, { file }]) => {
        // We use stringify to safely escape file paths for Windows/Unix compatibility
        return `    ${JSON.stringify(name)}: () => import(${JSON.stringify(file)})`;
      })
      .join(",\n");

    // We return a standard JS module that exports:
    // 1. A dictionary of dynamic components
    // 2. A Vue plugin (default export) to register them globally automatically
    return template.replace("{{imports}}", imports);
  }

  return {
    name: "vite-opensya-components",
    enforce: "pre",

    resolveId(id) {
      if (id === VIRTUAL_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;

      return generateCode();
    },
  };
}
