import type { Plugin } from "vite";
import { getListOpensyaConfig } from "../../../config/load.js";
import fs from "node:fs";
import { getChildren } from "../../../utils/get-children.js";
import path from "node:path";
import _ from "lodash";
import { getDirs } from "#core/utils/dirs.js";

const VIRTUAL_ID = "virtual:plugins";
const RESOLVED_VIRTUAL_ID = "\0virtual:plugins";

const template = `
{{imports}}

export const plugins = [
{{pluginArray}}
];

export const pluginsPlugin = {
  async install(app) {
    for (const [name, plugin] of Object.entries(plugins)) {
      if (typeof plugin === 'function') {
        // Supports both synchronous and asynchronous plugins
        await plugin({ app });
      } else if (plugin && typeof plugin.install === 'function') {
        await plugin.install(app);
      }
    }
    console.log('[Opensya] Registered app plugins:', Object.keys(plugins));
  }
};
`;

const dtsTemplate = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-opensya-plugins

declare global {
  const defineVuePlugin: (typeof import("#core/plugins/vite/app/helpers/plugin.js"))['defineVuePlugin'];
}

export {};
`;

export function vitePluginsPlugin(): Plugin {
  // Key: Plugin variable name, Value: Absolute file path
  let pluginEntries: Record<string, string> = {};

  // Converts a file path into a valid JS variable name (CamelCase)
  function getPluginVariableName(parentDir: string, filePath: string): string {
    const baseName = path
      .relative(parentDir, filePath)
      .replace(/\.global.(ts|js)$/, "");

    return (
      baseName
        .replace(/[-_\/]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ""))
        .replace(/^(.)/, (char) => char.toLowerCase()) + "Plugin"
    );
  }

  async function getPlugins(parentDir: string) {
    if (!fs.existsSync(parentDir)) return;

    // Scan all files ending with .ts or .js (excluding .d.ts)
    const files = getChildren(parentDir, {
      recursive: true,
      onlyFile: true,
      endWith: /\.global.(ts|js)$/,
    });

    for (const file of files) {
      if (file.path.endsWith(".d.ts")) continue;

      const varName = getPluginVariableName(parentDir, file.path);
      pluginEntries[varName] = file.path;
    }
  }

  // Generates the virtual:plugins declaration file
  async function generateDtsFile(): Promise<void> {
    const { OUTPUT_DIR_CLIENT } = getDirs();
    const dtsPath = path.resolve(OUTPUT_DIR_CLIENT, "plugins.d.ts");

    try {
      fs.writeFileSync(dtsPath, dtsTemplate, "utf-8");
    } catch (error) {
      console.error("[Vite Plugin] Failed to write plugins.d.ts:", error);
    }
  }

  async function generateCode(): Promise<string> {
    pluginEntries = {};

    const configs = _.reverse(getListOpensyaConfig());

    for (const { _srcDir } of configs) {
      const pluginsDir = path.resolve(_srcDir, "app/plugins");
      if (!fs.existsSync(pluginsDir)) continue;

      await getPlugins(pluginsDir);
    }

    // Write TS declarations
    await generateDtsFile();

    // 1. Generate Static Imports (e.g., import myPluginPlugin from "path/to/plugin.ts")
    const imports = Object.entries(pluginEntries)
      .map(([varName, filePath]) => {
        return `import ${varName} from ${JSON.stringify(filePath)};`;
      })
      .join("\n");

    // 2. Generate the key-value dictionary for the array
    const pluginArray = Object.keys(pluginEntries)
      .map((varName) => `  ${varName}: ${varName}`)
      .join(",\n");

    return template
      .replace("{{imports}}", imports)
      .replace("{{pluginArray}}", pluginArray);
  }

  return {
    name: "vite-opensya-plugins",
    enforce: "pre",

    resolveId(id) {
      if (id === VIRTUAL_ID) {
        return RESOLVED_VIRTUAL_ID;
      }
    },

    async load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return null;

      return generateCode();
    },
  };
}
