import { defineTable } from "@opensya/persistence";

export default defineTable({
  name: "roles",
  collectionName: "roles",
  columns: [
    {
      name: "id",
      columnName: "id",
      type: "uuid",
      nullable: false,
      primaryKey: true,
      unique: true,
      default: () => crypto.randomUUID(),
      validators: [],
    },
    {
      name: "name",
      columnName: "name",
      type: "string",
      nullable: false,
      primaryKey: false,
      unique: false,
      validators: [],
    },
    {
      name: "slug",
      columnName: "slug",
      type: "string",
      nullable: false,
      primaryKey: false,
      unique: true,
      validators: [],
    },
    {
      name: "description",
      columnName: "description",
      type: "text",
      nullable: true,
      primaryKey: false,
      unique: false,
      validators: [],
    },
    {
      name: "isSystem",
      columnName: "is_system",
      type: "boolean",
      nullable: false,
      primaryKey: false,
      unique: false,
      default: false,
      validators: [],
    },
    {
      name: "createdAt",
      columnName: "created_at",
      type: "timestamp",
      nullable: false,
      primaryKey: false,
      unique: false,
      default: () => new Date(),
      validators: [],
    },
  ],
  relations: [
    {
      name: "memberships",
      kind: "oneToMany",
      target: "memberships",
      foreignKey: "roleId",
      references: "id",
    },
    {
      name: "permissions",
      kind: "manyToMany",
      target: "permissions",
      through: {
        table: "role_permissions",
        sourceForeignKey: "roleId",
        targetForeignKey: "permissionId",
      },
      sourceKey: "id",
      targetKey: "id",
    },
    {
      name: "teamMemberships",
      kind: "oneToMany",
      target: "team_memberships",
      foreignKey: "roleId",
      references: "id",
    },
  ],
  tableValidators: [],
});
