import { defineTable } from "@opensya/persistence";

export default defineTable({
  name: "teams",
  collectionName: "teams",
  columns: [
    {
      name: "id",
      columnName: "id",
      type: "uuid",
      nullable: false,
      primaryKey: true,
      unique: true,
      default: () => crypto.randomUUID(),
      validators: [],
    },
    {
      name: "name",
      columnName: "name",
      type: "string",
      nullable: false,
      primaryKey: false,
      unique: false,
      validators: [],
    },
    {
      name: "slug",
      columnName: "slug",
      type: "string",
      nullable: false,
      primaryKey: false,
      unique: true,
      validators: [],
    },
    {
      name: "description",
      columnName: "description",
      type: "text",
      nullable: true,
      primaryKey: false,
      unique: false,
      validators: [],
    },
    {
      name: "createdAt",
      columnName: "created_at",
      type: "timestamp",
      nullable: false,
      primaryKey: false,
      unique: false,
      default: () => new Date(),
      validators: [],
    },
    {
      name: "updatedAt",
      columnName: "updated_at",
      type: "timestamp",
      nullable: false,
      primaryKey: false,
      unique: false,
      default: () => new Date(),
      validators: [],
    },
  ],
  relations: [
    {
      name: "memberships",
      kind: "oneToMany",
      target: "team_memberships",
      foreignKey: "teamId",
      references: "id",
    },
  ],
  tableValidators: [],
});
